### ISSUE TITLE
XMLElement children manipulation randomly breaks

### ISSUE THREAD

**Issue by eliias** [y-crdt/yrb#38]
# Problem

Manipulating an `XMLElement` randomly breaks (observed in flaky tests). It is possible that the manipulation isn't done properly on the Ruby side or that we have some memory mapping issues between Ruby and Rust.

## Examples

```bash
Failures:

  1) Y::XMLElement when changing commits automatically
     Failure/Error: expect(changes[0].first[:added].map(&:tag)).to match_array(%w[A B C])

       expected collection contained:  ["A", "B", "C"]
       actual collection contained:    ["\u0000", "A", "C"]
       the missing elements were:      ["B"]
       the extra elements were:        ["\u0000"]
     # ./spec/y/yxml_element_spec.rb:324:in `block (3 levels) in <top (required)>'
```

Job: https://github.com/y-crdt/yrb/actions/runs/3234322746/jobs/5297285225

```bash
Failures:

  1) Y::XMLElement when changing commits automatically
     Failure/Error: expect(changes[0].first[:added].map(&:tag)).to match_array(%w[A B C])

       expected collection contained:  ["A", "B", "C"]
       actual collection contained:    ["\n", "A", "C"]
       the missing elements were:      ["B"]
       the extra elements were:        ["\n"]
     # ./spec/y/xml_element_spec.rb:324:in `block (3 levels) in <top (required)>'
```

Job: https://github.com/y-crdt/yrb/actions/runs/3287990605/jobs/5417793161

```bash
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/hannesmoser/.cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.12.0/src/types/xml.rs:110:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

fatal: called `Option::unwrap()` on a `None` value

  0) Y::XMLElement when changing commits automatically
     Failure/Error: yxml_element_tag

     fatal:
       called `Option::unwrap()` on a `None` value
     # ./lib/y/xml.rb:237:in `yxml_element_tag'
     # ./lib/y/xml.rb:237:in `tag'
     # ./spec/y/xml_element_spec.rb:320:in `map'
     # ./spec/y/xml_element_spec.rb:320:in `block (3 levels) in <top (required)>'
```

### Analysis

For whatever reason, some of the (XML) elements that are forwarded to Ruby are no longer in memory when we access them. The container is there `Y::XMLElement`, but when accessing the `tag`, we get a different set of errors.

```
pub fn tag(&self) -> &str {
  let inner = &self.0 .0;
  inner.name.as_ref().unwrap()
}
```

When I add `GC.start` after the observer is attached, I can reliably produce the issues. I think this confirms that the elements emitted by change events are no longer accessible due to being garbage collected.

```
# garbage collect immediately
GC.start
```

There is some documentation about this in `magnus`. We are required to keep values on the stack, and I think it is impossible, because if we delete an element, it actually gets removed from the CRDT, and we just pass it to the callback and eventually access it later on. In other words, in order for the observer pattern to work, I need to control garbage collection 🤷.
https://github.com/matsadler/magnus#safety

**Comment by eliias** [comment]
It also seems to fail if applied directly in Rust:

```rust
use yrs::updates::decoder::Decode;
use yrs::{Doc, Update};

fn main() {
    let diffs: Vec<Vec<u8>> = vec![
        vec![
            1, 3, 197, 134, 244, 186, 10, 0, 7, 1, 7, 100, 101, 102, 97, 117, 108, 116, 3, 9, 112,
            97, 114, 97, 103, 114, 97, 112, 104, 7, 0, 197, 134, 244, 186, 10, 0, 6, 4, 0, 197,
            134, 244, 186, 10, 1, 1, 115, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 3, 132, 197, 134, 244, 186, 10, 2, 3, 227, 129, 149, 1,
            197, 134, 244, 186, 10, 1, 2, 1,
        ],
        vec![
            1, 4, 197, 134, 244, 186, 10, 0, 7, 1, 7, 100, 101, 102, 97, 117, 108, 116, 3, 9, 112,
            97, 114, 97, 103, 114, 97, 112, 104, 7, 0, 197, 134, 244, 186, 10, 0, 6, 1, 0, 197,
            134, 244, 186, 10, 1, 1, 132, 197, 134, 244, 186, 10, 2, 3, 227, 129, 149, 1, 197, 134,
            244, 186, 10, 1, 2, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 4, 132, 197, 134, 244, 186, 10, 3, 1, 120, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 5, 132, 197, 134, 244, 186, 10, 4, 3, 227, 129, 129, 1,
            197, 134, 244, 186, 10, 1, 4, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 6, 132, 197, 134, 244, 186, 10, 5, 1, 107, 0,
        ],
        vec![
            1, 2, 197, 134, 244, 186, 10, 4, 129, 197, 134, 244, 186, 10, 3, 1, 132, 197, 134, 244,
            186, 10, 4, 3, 227, 129, 129, 1, 197, 134, 244, 186, 10, 1, 4, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 7, 132, 197, 134, 244, 186, 10, 6, 3, 227, 129, 147, 1,
            197, 134, 244, 186, 10, 1, 6, 1,
        ],
        vec![
            1, 2, 197, 134, 244, 186, 10, 6, 129, 197, 134, 244, 186, 10, 5, 1, 132, 197, 134, 244,
            186, 10, 6, 3, 227, 129, 147, 1, 197, 134, 244, 186, 10, 1, 6, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 8, 132, 197, 134, 244, 186, 10, 7, 1, 114, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 9, 132, 197, 134, 244, 186, 10, 8, 3, 227, 130, 140, 1,
            197, 134, 244, 186, 10, 1, 8, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 8, 132, 197, 134, 244, 186, 10, 7, 1, 114, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 10, 132, 197, 134, 244, 186, 10, 9, 1, 107, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 11, 132, 197, 134, 244, 186, 10, 10, 3, 227, 129, 139, 1,
            197, 134, 244, 186, 10, 1, 10, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 12, 132, 197, 134, 244, 186, 10, 11, 1, 114, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 13, 132, 197, 134, 244, 186, 10, 12, 3, 227, 130, 137, 1,
            197, 134, 244, 186, 10, 1, 12, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 9, 132, 197, 134, 244, 186, 10, 8, 3, 227, 130, 140, 1,
            197, 134, 244, 186, 10, 1, 8, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 10, 132, 197, 134, 244, 186, 10, 9, 1, 107, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 11, 132, 197, 134, 244, 186, 10, 10, 3, 227, 129, 139, 1,
            197, 134, 244, 186, 10, 1, 10, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 12, 132, 197, 134, 244, 186, 10, 11, 1, 114, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 14, 132, 197, 134, 244, 186, 10, 13, 1, 98, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 16, 132, 197, 134, 244, 186, 10, 15, 1, 103, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 15, 132, 197, 134, 244, 186, 10, 14, 3, 227, 129, 176, 1,
            197, 134, 244, 186, 10, 1, 14, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 17, 132, 197, 134, 244, 186, 10, 16, 3, 227, 129, 144, 1,
            197, 134, 244, 186, 10, 1, 16, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 17, 132, 197, 134, 244, 186, 10, 16, 3, 227, 129, 144, 1,
            197, 134, 244, 186, 10, 1, 16, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 18, 132, 197, 134, 244, 186, 10, 17, 6, 227, 131, 144,
            227, 130, 176, 1, 197, 134, 244, 186, 10, 2, 15, 1, 17, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 20, 132, 197, 134, 244, 186, 10, 19, 1, 103, 0,
        ],
        vec![
            1, 3, 197, 134, 244, 186, 10, 13, 132, 197, 134, 244, 186, 10, 12, 3, 227, 130, 137,
            129, 197, 134, 244, 186, 10, 13, 1, 132, 197, 134, 244, 186, 10, 14, 4, 227, 129, 176,
            103, 1, 197, 134, 244, 186, 10, 2, 12, 1, 14, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 21, 132, 197, 134, 244, 186, 10, 20, 3, 227, 129, 140, 1,
            197, 134, 244, 186, 10, 1, 20, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 23, 132, 197, 134, 244, 186, 10, 22, 3, 227, 129, 170, 1,
            197, 134, 244, 186, 10, 1, 22, 1,
        ],
        vec![
            1, 3, 197, 134, 244, 186, 10, 18, 132, 197, 134, 244, 186, 10, 17, 6, 227, 131, 144,
            227, 130, 176, 129, 197, 134, 244, 186, 10, 19, 1, 132, 197, 134, 244, 186, 10, 20, 3,
            227, 129, 140, 1, 197, 134, 244, 186, 10, 3, 15, 1, 17, 1, 20, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 24, 132, 197, 134, 244, 186, 10, 23, 3, 227, 129, 132, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 22, 132, 197, 134, 244, 186, 10, 21, 1, 110, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 26, 132, 197, 134, 244, 186, 10, 25, 3, 227, 129, 139, 1,
            197, 134, 244, 186, 10, 1, 25, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 25, 132, 197, 134, 244, 186, 10, 24, 1, 107, 0,
        ],
        vec![
            1, 4, 197, 134, 244, 186, 10, 22, 129, 197, 134, 244, 186, 10, 21, 1, 132, 197, 134,
            244, 186, 10, 22, 6, 227, 129, 170, 227, 129, 132, 129, 197, 134, 244, 186, 10, 24, 1,
            132, 197, 134, 244, 186, 10, 25, 3, 227, 129, 139, 1, 197, 134, 244, 186, 10, 2, 22, 1,
            25, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 27, 132, 197, 134, 244, 186, 10, 26, 1, 100, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 28, 132, 197, 134, 244, 186, 10, 27, 3, 227, 129, 169, 1,
            197, 134, 244, 186, 10, 1, 27, 1,
        ],
        vec![
            1, 2, 197, 134, 244, 186, 10, 27, 129, 197, 134, 244, 186, 10, 26, 1, 132, 197, 134,
            244, 186, 10, 27, 3, 227, 129, 169, 1, 197, 134, 244, 186, 10, 1, 27, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 29, 132, 197, 134, 244, 186, 10, 28, 3, 227, 129, 134, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 30, 132, 197, 134, 244, 186, 10, 29, 1, 107, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 29, 132, 197, 134, 244, 186, 10, 28, 3, 227, 129, 134, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 31, 132, 197, 134, 244, 186, 10, 30, 3, 227, 129, 139, 1,
            197, 134, 244, 186, 10, 1, 30, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 30, 132, 197, 134, 244, 186, 10, 29, 1, 107, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 31, 132, 197, 134, 244, 186, 10, 30, 3, 227, 129, 139, 1,
            197, 134, 244, 186, 10, 1, 30, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 32, 135, 197, 134, 244, 186, 10, 0, 3, 9, 112, 97, 114,
            97, 103, 114, 97, 112, 104, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 32, 135, 197, 134, 244, 186, 10, 0, 3, 9, 112, 97, 114,
            97, 103, 114, 97, 112, 104, 0,
        ],
        vec![
            1, 2, 197, 134, 244, 186, 10, 33, 7, 0, 197, 134, 244, 186, 10, 32, 6, 4, 0, 197, 134,
            244, 186, 10, 33, 1, 107, 0,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 35, 132, 197, 134, 244, 186, 10, 34, 3, 227, 129, 139, 1,
            197, 134, 244, 186, 10, 1, 34, 1,
        ],
        vec![
            1, 1, 197, 134, 244, 186, 10, 36, 132, 197, 134, 244, 186, 10, 35, 1, 107, 0,
        ],
    ];

    let doc = Doc::new();
    let mut txn = doc.transact();
    for diff in diffs {
        Update::decode_v1(diff.as_slice())
            .map(|update| txn.apply_update(update))
            .expect("applying update failed");
    }
}
```

**Comment by eliias** [comment]
This issue seems to not happen anymore at all after the major changes done in the yrs 0.13.x+ implementation.
